global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'shwetabharambe2196@gmail.com'
  smtp_auth_username: 'shwetabharambe2196@gmail.com'
  smtp_auth_password: 'hjoc gwzj hcqm xfwu'

route:
  receiver: email

receivers:
  - name: email
    email_configs:
      - to: 'shwetabharambe2196@gmail.com'
        send_resolved: true