global:
  scrape_interval: 15s

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "automation-lab"

    metrics_path: /metrics

    static_configs:
      - targets:
          - automation-lab-alb-1405700921.us-east-1.elb.amazonaws.com