name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: automation-lab
  ECS_CLUSTER: automation-lab-cluster
  ECS_SERVICE: automation-lab-service

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r app/requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          python -m pytest